Update Find Person
AY2425S1-CS2103T-W10-2/tp pull request #149
Opened 2024-10-27 08:46 UTC by rxchell

Fixes #104

2024-10-29 15:35 UTC, Vangmay reviewed
LGTM. Just a minor nit

2024-10-29 15:35 UTC, Vangmay commented on src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
> +     * Returns a composed {@code Predicate}, given the argument multimap.
Can we add @throws and @argument tags here for code quality?

2024-10-29 15:46 UTC, Vangmay requested changes

2024-10-29 15:46 UTC, Vangmay commented on src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
> +        assertDoesNotThrow(() -> parser.parse(" person n/John"));
Would a better success criteria be to check if John has been parsed correctly?

2024-10-30 05:15 UTC, jayjay19630 requested changes
LGTM, just one minor change requested and one merge conflict that needs to be resolved.

2024-10-30 05:15 UTC, jayjay19630 commented on src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
> +     */
Thanks for writing the JavaDocs for these methods!

2024-10-30 05:15 UTC, jayjay19630 commented on src/main/java/seedu/address/logic/commands/FindPersonCommand.java
> +            + "Parameters: n/[NAME]\n"
Do you think we can change this so that it sticks to the parameter formatting we have? (i.e. "[" + PREFIX_NAME + "NAME]"

2024-10-30 06:40 UTC, jayjay19630 approved these changes
Thanks for the changes!

2024-10-30 06:44 UTC, merged