Update Model section of developer guide
AY2425S1-CS2103T-W10-2/tp pull request #80
Opened 2024-10-15 16:33 UTC by zaidansani

Resolves #79 

Reflected new AppointmentBook model, as well as changes to existing Person model.

2024-10-16 08:25 UTC, rxchell requested changes

2024-10-16 08:25 UTC, rxchell commented on docs/diagrams/ModelClassDiagram.puml
LGTM. 

The diagram appears fine in puml, but the arrows appear different in the docs.

Screenshot of the docs (some arrows are not pointing to their corresponding class)
<img width="1215" alt="Screenshot 2024-10-16 at 16 14 31" src="https://github.com/user-attachments/assets/93111945-be42-494e-9287-b6a431d9155b">

2024-10-16 08:25 UTC, rxchell commented on docs/diagrams/BetterModelClassDiagram.puml
For the description if the BetterModelClassDiagram under **Note:** (line 140), the "`Tag` list in the `AddressBook`" can be specified to be `UniqueTagList`

2024-10-17 15:50 UTC, zaidansani commented on docs/diagrams/ModelClassDiagram.puml
This is a weird issue, no idea whats the issue

2024-10-18 08:39 UTC, rxchell approved these changes
LGTM!

2024-10-18 08:39 UTC, merged